# fly.toml app configuration file generated for ad-server on 2025-08-22T17:04:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ad-server'
primary_region = 'ams'

[deploy]
strategy = "rolling"

[env]
DATABASE_URL = "sqlite:////data/adserver.db"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = 'ad_data'
destination = '/data'

[experimental]
auto_rollback = true
